// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql"
	"time"
)

type PoutboxCursor struct {
	ID                         int32
	LastProcessedID            int64
	LastProcessedAt            time.Time
	LastProcessedTransactionID int64
	UpdatedAt                  time.Time
}

type PoutboxDeadLetter struct {
	ID           int64
	Payload      []byte
	ErrorMessage sql.NullString
	RetryCount   int32
	FailedAt     time.Time
	DeadAt       time.Time
}

type PoutboxFailed struct {
	ID           int64
	Payload      []byte
	ErrorMessage sql.NullString
	RetryCount   int32
	FailedAt     time.Time
	NextRetryAt  time.Time
}

type PoutboxImmediate struct {
	ID            int64
	Payload       []byte
	CreatedAt     time.Time
	TransactionID int64
}

type PoutboxPartitionMetum struct {
	PartitionName string
	RangeStart    time.Time
	RangeEnd      time.Time
	CreatedAt     time.Time
}

type PoutboxScheduled struct {
	ID           int64
	Payload      []byte
	ScheduledAt  time.Time
	CreatedAt    time.Time
	ErrorMessage sql.NullString
}
