CREATE SCHEMA IF NOT EXISTS "poutbox";

CREATE TABLE IF NOT EXISTS "poutbox".immediate(
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    payload TEXT NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    transaction_id bigint NOT NULL DEFAULT txid_current(),
    PRIMARY KEY(created_at, id)
) PARTITION BY RANGE(created_at);

CREATE INDEX IF NOT EXISTS immediate_id_idx ON "poutbox".immediate(id);
CREATE INDEX IF NOT EXISTS immediate_transaction_idx ON "poutbox".immediate(transaction_id, id);
CREATE INDEX IF NOT EXISTS immediate_created_transaction_idx ON "poutbox".immediate(created_at, transaction_id, id);

CREATE TABLE IF NOT EXISTS "poutbox".partition_meta (
    partition_name TEXT PRIMARY KEY,
    range_start TIMESTAMPTZ(6) NOT NULL,
    range_end TIMESTAMPTZ(6) NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE IF NOT EXISTS "poutbox".cursor (
    id INT PRIMARY KEY DEFAULT 1,
    last_processed_id BIGINT NOT NULL DEFAULT 0,
    last_processed_at TIMESTAMPTZ(6) NOT NULL DEFAULT '1970-01-01'::timestamptz,
    last_processed_transaction_id bigint NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    CONSTRAINT cursor_single_row CHECK (id = 1)
);

INSERT INTO "poutbox".cursor (id, last_processed_id, last_processed_at, last_processed_transaction_id) VALUES (1, 0, '1970-01-01'::timestamptz(6), 0) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "poutbox".failed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload TEXT NOT NULL,
    error_message TEXT,
    retry_count INT NOT NULL DEFAULT 0,
    failed_at TIMESTAMPTZ(6) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    next_retry_at TIMESTAMPTZ(6) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX IF NOT EXISTS failed_retry_idx ON "poutbox".failed (next_retry_at, id);


CREATE TABLE IF NOT EXISTS "poutbox".dead_letter (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	payload TEXT NOT NULL,
	error_message TEXT,
	retry_count INT NOT NULL,
	failed_at TIMESTAMPTZ(6) NOT NULL,
	dead_at TIMESTAMPTZ(6) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE IF NOT EXISTS "poutbox".scheduled (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	payload TEXT NOT NULL,
	scheduled_at TIMESTAMPTZ(6) NOT NULL,
	created_at TIMESTAMPTZ(6) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX IF NOT EXISTS scheduled_ready_idx ON "poutbox".scheduled (scheduled_at, id);


